config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "groups#index"

  resources :groups do
    resources :messages do
      resources :comments
    end
  end

  resources :rooms do
    resources :chats
  end

  resources :timelines do
    resources :reviews
  end

  resources :users
  resources :buildings


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/building.rb
class Building < ApplicationRecord

  validates :facility, :explanation, :access, :telephone_number, presence: true
  validates :facility, uniqueness: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

  def roomname
    str = "/"
    users.each do |user|
      roomname = "#{user.name}" + str
    end
    return roomname
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :message
  belongs_to :group


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/group.rb
class Group < ApplicationRecord


  has_many :messages, dependent: :destroy
  has_many :users, through: :members
  has_many :members
  has_many :comments

  accepts_nested_attributes_for :messages, allow_destroy: true


  has_attached_file :image, styles: { original: "100x100>", medium: "50x50#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

  def memberlist
    str = "Member: "
    users.each do |user|
      str += "#{user.name}"
    end
    return str
  end
end

app/models/member.rb
class Member < ApplicationRecord

  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord

  validates :text, length: { minimum: 1 }

  belongs_to :group
  belongs_to :user
  has_many :comments

  accepts_nested_attributes_for :comments, allow_destroy: true


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :timeline
  belongs_to :user


  has_attached_file :image, styles: { original: "600x600>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users, through: :roommates
  has_many :roommates
  has_many :chats

  accepts_nested_attributes_for :chats, allow_destroy: true

  def friends
    room = self.primary_key = "room_id"
    users.each do |user|
      room += "#{user.name}"
    end
    return room
  end
end

app/models/roommate.rb
class Roommate < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  has_many :reviews
  belongs_to :user

  accepts_nested_attributes_for :reviews, allow_destroy: true

  has_attached_file :image, styles: { original: "600x600>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, :place, :year, uniqueness: true
  validates :name, :place, :year, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages, dependent: :destroy
  has_many :groups, through: :members
  has_many :members
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :roommates
  has_many :roommates
  has_many :timelines
  has_many :comments
  has_many :reviews


  has_attached_file :image, styles: { original: "100x100>", short: "70x70>", medium: "50x50#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Mirrorchat
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/module/_group-header.html.haml
= link_to group_path(group) do
  %span
    = image_tag group.image.url(:medium), class: "group-image-tag"
    = group.name
  - if (current_user.role == "Leader") || (current_user.role == "Subleader")
    = link_to group_path(group), method: :delete do
      %i.fa.fa-sign-out{"aria-hidden" => "true"}
    = link_to edit_group_path(group) do
      %i.fa.fa-pencil-square-o{"aria-hidden" => "true"}

app/views/module/_groupsidemenu.html.haml
.left_content
  .main_character.clearfix
    %h1
      = current_user.name
    = link_to edit_user_registration_path do
      %i.fa.fa-cog{"aria-hidden" => "true"}
    = link_to new_group_path do
      %i.fa.fa-users{"aria-hidden" => "true"}
    = link_to buildings_path do
      %i.fa.fa-building{"aria-hidden" => "true"}
    = link_to root_path do
      %i.fa.fa-home{"aria-hidden" => "true"}
  .group_search.clearfix
    = label :group, "グループを検索してください", class: "group--search__label"
    = text_field :group, :name, class: "group-search-form__input"
    = button_tag type: 'submit', class: "group-search-btn" do
      %i.fa.fa-search{"aria-hidden" => "true"}
  .groups_view
    %span グループ
    - @groups.each do |group|
      = link_to group_messages_path(group) do
        .group.clearfix
          %i.fa.fa-comments{"aria-hidden" => "true"}
          %span
            = group.name
  .friends_view
    %span 友達
    - @users.each do |user|
      = link_to chat_user_messages_path(user) do
        .friend.clearfix
          %i.fa.fa-comments{"aria-hidden" => "true"}
          %span
            = user.name

app/views/module/_sidemenu.html.haml
.left_content
  .main_character.clearfix
    = link_to edit_user_registration_path do
      %h1
        = image_tag current_user.image.url(:thumb),class: "user-image-tag"
        = current_user.name
    = link_to timelines_path do
      %i.fa.fa-book{"aria-hidden" => "true"}
    = link_to new_group_path do
      %i.fa.fa-users{"aria-hidden" => "true"}
    = link_to buildings_path do
      %i.fa.fa-building{"aria-hidden" => "true"}
    = link_to root_path do
      %i.fa.fa-home{"aria-hidden" => "true"}
  .group_search.clearfix
    = label :group, "グループを検索してください", class: "group--search__label"
    = search_field :group, :name, class: "group-search-form__input"
    = button_tag type: 'submit', class: "group-search-btn" do
      %i.fa.fa-search{"aria-hidden" => "true"}
  .friend_search.clearfix
    = label :user, "友達を検索してください", class: "friend--search__label"
    = search_field :user, :name, class: "friend-search-form__input"
    = button_tag type: 'submit', class: "friend-search-btn" do
      %i.fa.fa-search{"aria-hidden" => "true"}
  .groups_view
    %span グループ
    - groups.each do |group|
      - if group.status == "Open"
        = link_to group_messages_path(group) do
          .group.clearfix
            %i.fa.fa-comments{"aria-hidden" => "true"}
            %span
              = image_tag group.image.url(:thumb), class: "group-image-tag"
              = group.name
  .friends_view
    %span 友達
    - rooms.each do |room|
      = link_to room_chats_path(room) do
        .friend.clearfix
          %i.fa.fa-comments{"aria-hidden" => "true"}
          %span
            = room.name