config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "groups#index"

  resources :groups do
    resources :messages do
      resources :comments
    end
  end

  resources :rooms do
    resources :chats
  end

  resources :timelines do
    resources :reviews
  end

  resources :users
  resources :buildings


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord

  validates :facility, :explanation, :access, :telephone_number, presence: true
  validates :facility, uniqueness: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

  def roomname
    str = "/"
    users.each do |user|
      roomname = "#{user.name}" + str
    end
    return roomname
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :message
  belongs_to :group


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/group.rb
class Group < ApplicationRecord


  has_many :messages, dependent: :destroy
  has_many :users, through: :members
  has_many :members
  has_many :comments

  accepts_nested_attributes_for :messages, allow_destroy: true


  has_attached_file :image, styles: { original: "100x100>", medium: "50x50#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

  def memberlist
    str = "Member: "
    users.each do |user|
      str += "#{user.name}"
    end
    return str
  end
end

app/models/member.rb
class Member < ApplicationRecord

  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord

  validates :text, length: { minimum: 1 }

  belongs_to :group
  belongs_to :user
  has_many :comments

  accepts_nested_attributes_for :comments, allow_destroy: true


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :timeline
  belongs_to :user


  has_attached_file :image, styles: { original: "600x600>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users, through: :roommates
  has_many :roommates
  has_many :chats

  accepts_nested_attributes_for :chats, allow_destroy: true

  def friends
    room = self.primary_key = "room_id"
    users.each do |user|
      room += "#{user.name}"
    end
    return room
  end
end

app/models/roommate.rb
class Roommate < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  has_many :reviews
  belongs_to :user

  accepts_nested_attributes_for :reviews, allow_destroy: true

  has_attached_file :image, styles: { original: "600x600>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, :place, :year, uniqueness: true
  validates :name, :place, :year, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages, dependent: :destroy
  has_many :groups, through: :members
  has_many :members
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :roommates
  has_many :roommates
  has_many :timelines
  has_many :comments
  has_many :reviews


  has_attached_file :image, styles: { original: "100x100>", short: "70x70>", medium: "50x50#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @groups = Group.order("created_at ASC")
    @rooms = Room.order("created_at ASC")
    @group = Group.find(params[:group_id])
    @message = Message.find(params[:message_id])
    @comment = Comment.new
  end

  def create
    @group = Group.find(params[:group_id])
    @message = Message.find(params[:message_id])
    @comment = Comment.new
    @message_comment = @message.comments.create(comment_params)

    if @message_comment
        redirect_to group_message_comments_path([@group, @message])
    else
      render :index
    end
  end

  def edit
    @groups = Group.order("created_at ASC")
    @rooms = Room.order("created_at ASC")
    @comment = Comment.find(params[:id])
  end

  def update
  end

  def destroy
    @group = Group.find(params[:group_id])
    @message = Message.find(params[:message_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to group_message_comments_path([@group, @message])
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :image).merge(group_id: params[:group_id], message_id: params[:message_id], user_id: current_user.id)
  end

  def update_comment_params
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
- message.comments.each do |comment|
  .comment.clearfix
    %span
      = image_tag comment.user.image.url(:thumb), class: "user-image"
      = link_to user_path(comment.user_id) do
        = comment.user.name
      = comment.created_at.strftime("%Y/%m/%d/ %H:%M:%S")
    - if comment.user_id == current_user.id
      .comment-operate
        = link_to group_message_comment_path(group, message, comment), method: :delete do
          %i.fa.fa-times{"aria-hidden" => "true"}
        = link_to edit_group_message_comment_path(group, message, comment) do
          %i.fa.fa-pencil-square-o{"aria-hidden" => "true"}
    - if comment.image.present?
      %h4
        = image_tag comment.image.url(:medium)
    - if comment.text.present?
      %h5
        = comment.text

app/views/comments/edit.html.haml
.content.clearfix
  = render partial: 'module/sidemenu', locals: {groups: @groups, rooms: @rooms}

app/views/comments/index.html.haml
.content.clearfix
  = render partial: 'module/sidemenu', locals: {groups: @groups, rooms: @rooms}
  .right_content.clearfix
    .group_name.clearfix
      = render partial: 'module/group-header', locals: {group: @group}
    .message_view
      .chat.clearfix
        %span
          = image_tag @message.user.image.url(:thumb), class: "user-image-tag"
          = link_to user_path(@message.user_id) do
            = @message.user.name
        %p
          = @message.created_at.strftime("%Y/%m/%d %H:%M:%S")
        - if @message.user_id == current_user.id
          = link_to [@group, @message], method: :delete do
            %i.fa.fa-times{"aria-hidden" => "true"}
          = link_to edit_group_message_path(@group, @message) do
            %i.fa.fa-pencil-square-o{"aria-hidden" => "true"}
        - if @message.image.present?
          %h4
            = image_tag @message.image.url(:medium)
        - if @message.text.present?
          %h5
            = @message.text

    .comment-form
      = form_for([@group, @message, @comment]) do |f|
        = f.text_field :text, class: "comment-field", placeholder: "コメントしてください"
        = f.label :image, class: "comment_image_label"do
          = fa_icon 'picture-o', class: "comment_icon"
          = f.file_field :image, style: "display: none"
        = button_tag type: "submit", class: "comment-submit-button" do
          %i.fa.fa-paper-plane{"aria-hidden" => "true"}
    .comment-view
      - if @message.comments.exists?
        = render partial: 'comment', locals: {group: @group, message: @message}
      - else
        %p あなたが一番乗りです。コメントしましょう!!