config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "groups#index"

  resources :groups do
    resources :messages do
      resources :comments
    end
  end

  resources :rooms do
    resources :chats
  end

  resources :timelines do
    resources :reviews
  end

  resources :users
  resources :buildings


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord

  validates :facility, :explanation, :access, :telephone_number, presence: true
  validates :facility, uniqueness: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

  def roomname
    str = "/"
    users.each do |user|
      roomname = "#{user.name}" + str
    end
    return roomname
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :message
  belongs_to :group


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/group.rb
class Group < ApplicationRecord


  has_many :messages, dependent: :destroy
  has_many :users, through: :members
  has_many :members
  has_many :comments

  accepts_nested_attributes_for :messages, allow_destroy: true


  has_attached_file :image, styles: { original: "100x100>", medium: "50x50#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

  def memberlist
    str = "Member: "
    users.each do |user|
      str += "#{user.name}"
    end
    return str
  end
end

app/models/member.rb
class Member < ApplicationRecord

  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord

  validates :text, length: { minimum: 1 }

  belongs_to :group
  belongs_to :user
  has_many :comments

  accepts_nested_attributes_for :comments, allow_destroy: true


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :timeline
  belongs_to :user


  has_attached_file :image, styles: { original: "600x600>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users, through: :roommates
  has_many :roommates
  has_many :chats

  accepts_nested_attributes_for :chats, allow_destroy: true

  def friends
    room = self.primary_key = "room_id"
    users.each do |user|
      room += "#{user.name}"
    end
    return room
  end
end

app/models/roommate.rb
class Roommate < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  has_many :reviews
  belongs_to :user

  accepts_nested_attributes_for :reviews, allow_destroy: true

  has_attached_file :image, styles: { original: "600x600>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, :place, :year, uniqueness: true
  validates :name, :place, :year, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages, dependent: :destroy
  has_many :groups, through: :members
  has_many :members
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :roommates
  has_many :roommates
  has_many :timelines
  has_many :comments
  has_many :reviews


  has_attached_file :image, styles: { original: "100x100>", short: "70x70>", medium: "50x50#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  def index
    @groups = Group.order("created_at ASC")
    @rooms = Room.order("created_at ASC")
    @buildings = Building.order("created_at ASC").page(params[:page]).per(5)
  end

  def new
    @groups = Group.order("created_at ASC")
    @rooms = Room.order("created_at ASC")
    @building = Building.new
  end

  def create
    @building = Building.new(building_params)

    if @building.save
      redirect_to buildings_path
    end
  end

  def edit
    @groups = Group.order("created_at ASC")
    @rooms = Room.order("created_at ASC")
    @building = Building.find(params[:id])
  end

  def update
    @building = Building.find(params[:id])

    if @building.update(building_params)
      redirect_to buildings_path
    end
  end

  def destroy
    @building = Building.find(params[:id])
    @building.destroy
      redirect_to buildings_path
  end


  private
  def building_params
    params.require(:building).permit(:facility, :explanation, :access, :telephone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buildings/edit.html.haml
.content.clearfix
  = render partial: 'module/sidemenu', locals: {groups: @groups, rooms: @rooms}
  .right_content.clearfix
    = form_for(@building, id: 'new_building') do |f|
      - if @building.errors.any?
        .chat-group-form__errors
        %h2
          #{@building.errors.count}件のエラーが発生しました。
          %ul
            - @building.errors.full_messages.each do |full_message|
              %li #{full_message}
      .new-facility__information
        .new-facility__name
          = f.label :facility, "施設名", class: "facility-label"
          = f.text_field :facility, class: "facility-form", placeholder: "施設を入力してください"
        .new-facility__explanation
          = f.label :explanation, "説明", class: "explanation-label"
          = f.text_area :explanation, placeholder: "施設の説明をしてください", size: "100px", class: "explanation-form"
        .new-facility__access
          = f.label :access, "アクセス", class: "access-label"
          = f.text_field :access, class: "access-form"
        .new-facility__phone
          = f.label :telephone_number, "電話番号", class: "telephone-label"
          = f.text_field :telephone_number, class: "telephone-form"
        .save
          = f.submit "保存", class: "information-save"

app/views/buildings/index.html.haml
.content.clearfix
  = render partial: 'module/sidemenu', locals: {groups: @groups, rooms: @rooms}
  .right_content
    .facility
      .header
        %h1 施設検索
        %p お近くの公共機関、ショッピングセンターなどを紹介します。
      .new_facility.clearfix
        = link_to new_building_path do
          %h2 施設の追加
      .facility-search.clearfix
        = label :building, "施設を検索してください", class: "facility-search-label"
        = text_field :building, :facility, class: "facility-search-form"
        = button_tag type: 'submit', class: "facility-search-button" do
          %i.fa.fa-search{"aria-hidden" => "true"}
      #facility-search-result

    .facility__view.clearfix
      .facility-label
        = label :building, "検索結果", class: "search-result-label"
      .facility-result.clearfix
        - @buildings.each do |fac|
          .facility-information
            = link_to edit_building_path(fac) do
              %h2 編集
            = link_to building_path(fac), method: :delete do
              %h2 削除
            .facility__name
              %h1 施設名
              %p
                = fac.facility
            .facility__explanation
              %h1 施設説明
              %p
                = fac.explanation
            .facility__access
              %h1 アクセス
              %p
                = fac.access
            .facility__phone
              %h1 電話番号
              %p
                = fac.telephone_number
      .pagination.clearfix
        = paginate(@buildings)

app/views/buildings/new.html.haml
.content.clearfix
  = render partial: 'module/sidemenu', locals: {groups: @groups, rooms: @rooms}
  .right_content.clearfix
    = form_for(@building, id: 'new_building') do |f|
      - if @building.errors.any?
        .chat-group-form__errors
        %h2
          #{@building.errors.count}件のエラーが発生しました。
          %ul
            - @building.errors.full_messages.each do |full_message|
              %li #{full_message}
      .new-facility__information
        .new-facility__name
          = f.label :facility, "施設名", class: "facility-label"
          = f.text_field :facility, class: "facility-form", placeholder: "施設を入力してください"
        .new-facility__explanation
          = f.label :explanation, "説明", class: "explanation-label"
          = f.text_area :explanation, placeholder: "施設の説明をしてください", size: "100px", class: "explanation-form"
        .new-facility__access
          = f.label :access, "アクセス", class: "access-label"
          = f.text_field :access, class: "access-form"
        .new-facility__phone
          = f.label :telephone_number, "電話番号", class: "telephone-label"
          = f.text_field :telephone_number, class: "telephone-form"
        .save
          = f.submit "保存", class: "information-save"