config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "groups#index"

  resources :groups do
    resources :messages do
      resources :comments
    end
  end

  resources :rooms do
    resources :chats
  end

  resources :timelines do
    resources :reviews
  end

  resources :users
  resources :buildings


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord

  validates :facility, :explanation, :access, :telephone_number, presence: true
  validates :facility, uniqueness: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

  def roomname
    str = "/"
    users.each do |user|
      roomname = "#{user.name}" + str
    end
    return roomname
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :message
  belongs_to :group


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/group.rb
class Group < ApplicationRecord


  has_many :messages, dependent: :destroy
  has_many :users, through: :members
  has_many :members
  has_many :comments

  accepts_nested_attributes_for :messages, allow_destroy: true


  has_attached_file :image, styles: { original: "100x100>", medium: "50x50#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

  def memberlist
    str = "Member: "
    users.each do |user|
      str += "#{user.name}"
    end
    return str
  end
end

app/models/member.rb
class Member < ApplicationRecord

  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord

  validates :text, length: { minimum: 1 }

  belongs_to :group
  belongs_to :user
  has_many :comments

  accepts_nested_attributes_for :comments, allow_destroy: true


  has_attached_file :image, styles: { original: "1080x1920>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :timeline
  belongs_to :user


  has_attached_file :image, styles: { original: "600x600>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users, through: :roommates
  has_many :roommates
  has_many :chats

  accepts_nested_attributes_for :chats, allow_destroy: true

  def friends
    room = self.primary_key = "room_id"
    users.each do |user|
      room += "#{user.name}"
    end
    return room
  end
end

app/models/roommate.rb
class Roommate < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  has_many :reviews
  belongs_to :user

  accepts_nested_attributes_for :reviews, allow_destroy: true

  has_attached_file :image, styles: { original: "600x600>", medium: "300x300#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, :place, :year, uniqueness: true
  validates :name, :place, :year, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages, dependent: :destroy
  has_many :groups, through: :members
  has_many :members
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :roommates
  has_many :roommates
  has_many :timelines
  has_many :comments
  has_many :reviews


  has_attached_file :image, styles: { original: "100x100>", short: "70x70>", medium: "50x50#", thumb: "30x30#"}, default_url: "/images/:style/Masketeer.png", path: "#{Rails.root}/public/system/:class/image/:id.:style.:extension",
url:"/system/:class/image/:id.:style.:extension"

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}

end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController

  def index
    @groups = Group.order("created_at ASC")
    @rooms = Room.order("created_at ASC")
    @timeline = Timeline.new
    @timelines = Timeline.order("created_at DESC")
    @review = Review.new
  end

  def create
    @timeline = Timeline.new(timeline_params)

    if @timeline.save
      redirect_to timelines_path
    end
  end

  def edit
    @groups = Group.order("created_at ASC")
    @rooms = Room.order("created_at ASC")
    @timeline = Timeline.find(params[:id])
  end

  def update
    @timeline = Timeline.find(params[:id])

    if @timeline.update(timeline_params)
      redirect_to timelines_path
    end
  end

  def destroy
    @timeline = Timeline.find(params[:id])

    if @timeline.destroy
      redirect_to timelines_path
    end

  end

  private
  def timeline_params
    params.require(:timeline).permit(:text, :image, reviews_attributes: [:text, :image, :created_at]).merge(user_id: current_user.id)
  end

  def update_timeline_params
    params.require(:timeline).permit(:text, :image, reviews_attributes: [:text, :image, :created_at, :updated_at, :_destroy, :id]).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/timelines/_timeline.html.haml
= form_for(timeline) do |f|
  .timeline-form-header.clearfix
    %span
      = image_tag current_user.image.url(:thumb), class: "timeline-image"
    .timeline-name
      %h2
        = current_user.name
  .timeline-form-footer
    = f.text_area :text, class: "timeline__form", placeholder: "あなたが今日起こった出来事を書こう"
    = f.label :image, class: "timeline_image_label" do
      = fa_icon 'picture-o', class: "timeline_icon"
      = f.file_field :image, style: "display: none", class: "timeline_image"
    = button_tag type: "submit", class: "timeline_submit" do
      %i.fa.fa-paper-plane{"aria-hidden" => "true"}

app/views/timelines/edit.html.haml
.content.clearfix
  = render partial: 'module/sidemenu', locals: {groups: @groups, rooms: @rooms}

app/views/timelines/index.html.haml
.content.clearfix
  = render partial: 'module/sidemenu', locals: {groups: @groups, rooms: @rooms}
  .right_content
    .header
      %h1 タイムライン
    .middle
      .timeline-form
        = render partial: 'timelines/timeline', locals: {timeline: @timeline}
      .timeline_view
        - @timelines.each do |timeline|
          .timeline
            .timeline-semi-wrap
              .timeline-header.clearfix
                %span
                  = image_tag timeline.user.image.url(:thumb), class: "timeline-image"
                .timeline-info
                  %h3
                    = link_to user_path(timeline.user_id) do
                      = timeline.user.name
                    = timeline.created_at.strftime("%Y/%m/%d %H:%M:%S")
              .timeline-middle
                - if timeline.image.present?
                  %h4
                    = image_tag timeline.image.url(:original), class: "timeline-image"
                - if timeline.text.present?
                  %h5
                    = timeline.text
            - if timeline.user_id != current_user.id
              - if timeline.reviews.exists?
                .timeline-retweet.clearfix
                  = link_to timeline_reviews_path(timeline) do
                    .timeline-tuner
                      %i.fa.fa-retweet{"aria-hidden" => "true"}
                      %span
                        = timeline.reviews.count
              = form_for([timeline, @review]) do |f|
                .timeline-review-form
                  = f.text_field :text, class: "review__form", placeholder: "知り合いのタイムラインにコメントしよう"
                  = f.label :image, class: "review_image_label" do
                    = fa_icon 'picture-o', class: "review_icon"
                    = f.file_field :image, style: "display: none", class: "review_image"
                  = button_tag type: "submit", class: "review_submit" do
                    %i.fa.fa-paper-plane{"aria-hidden" => "true"}
            - if timeline.user_id == current_user.id
              .timeline-operate.clearfix
                .timeline-delete
                  = link_to timeline_path(timeline), method: :delete do
                    %i.fa.fa-times{"aria-hidden" => "true"}
                .timeline-edit
                  = link_to edit_timeline_path(timeline) do
                    %i.fa.fa-pencil-square-o{"aria-hidden" => "true"}
                - if timeline.reviews.exists?
                  .timeline-retweets
                    = link_to timeline_reviews_path(timeline) do
                      %i.fa.fa-retweet{"aria-hidden" => "true"}
                      %span
                        = timeline.reviews.count

    .footer